function picture = adjpredictionStep(picture,p)
%
% adjpredictionStep
%
% Copyright (C) 2005-2025 Shogo MURAMATSU, All rights reserved

if (mod(size(picture,1),2)==0)
    picture(end,:,:) = 2*picture(end,:,:);
    picture(1:2:end,:,:) = imlincomb(...
        p, [0*picture(2,:,:); picture(2:2:end-1,:,:)], ...
        1, picture(1:2:end,:,:), ...
        p, picture(2:2:end,:,:) ...
        );
    picture(end,:,:) = picture(end,:,:)/2;
else
    picture(1:2:end,:,:) = imlincomb(...
        p, [0*picture(2,:,:); picture(2:2:end-1,:,:)], ...
        1, picture(1:2:end,:,:), ...
        p, [picture(2:2:end,:,:); 0*picture(end-1,:,:)] ...
        );
end
end