function picture = adjupdateStep(picture,u)
%
% adjupdateStep
%
% Copyright (C) 2025 Shogo MURAMATSU, All rights reserved
%

picture(1,:,:) = 2*picture(1,:,:);
if (mod(size(picture,1),2)==0)
    picture(2:2:end,:,:) = imlincomb(...
        u, picture(1:2:end,:,:), ...
        1, picture(2:2:end,:,:), ...
        u, [picture(3:2:end,:,:); 0*picture(end-1,:,:)] ...
        );
else
    picture(end,:,:) = 2*picture(end,:,:);
    picture(2:2:end,:,:) = imlincomb(...
        u, picture(1:2:end-2,:,:), ...
        1, picture(2:2:end,:,:), ...
        u, picture(3:2:end,:,:) ...
        );
    picture(end,:,:) = picture(end,:,:)/2;
end
picture(1,:,:) = picture(1,:,:)/2;
end